vim.g.mapleader = '-' -- global leader
vim.g.maplocalleader = '-' -- local leader
vim.opt.mouse = '' -- disable the mouse entirely lol
vim.opt.grepprg = 'rg --vimgrep --no-heading --smart-case' -- grep command
vim.g.have_nerd_font = true -- does font support nerd chars
vim.opt.number = true -- line numbers
vim.opt.relativenumber = true -- relative line numbers
vim.opt.showmode = false -- hide mode (not sure if I should keep this)
vim.opt.breakindent = true -- make wrapped line continue on same indentation
vim.opt.ignorecase = true -- search behavior (ignore case at first)
vim.opt.smartcase = true -- search behavior (stop ignoring case if mixed case searched)
vim.o.hlsearch = false -- no highlight in search
vim.o.completeopt = 'menuone,noselect' -- set completeopt to have a better completion experience
vim.o.termguicolors = true -- term colors
vim.opt.encoding = 'utf-8' -- encoding
vim.opt.signcolumn = 'yes' -- sign column
vim.opt.wrap = false -- no wrap
vim.opt.updatetime = 16 -- decrease update tme
vim.opt.timeoutlen = 500 -- decrease sequence timeout
vim.opt.splitright = true -- enable how vertical splits should be opened (right)
vim.opt.splitbelow = true -- enable how horizontal splits should be opened (below)
vim.opt.autoread = true -- auto reload files when changed
vim.opt.colorcolumn = '100' -- show the 100 chars column
vim.opt.list = true -- sets how neovim will display certain whitespace characters in the editor
vim.opt.listchars = { tab = '» ', trail = '·', nbsp = '␣' } -- how those blank spaces should be displayed
vim.opt.inccommand = 'split' -- preview substitutions live
vim.opt.expandtab = true -- use space to indent
vim.opt.cursorline = true -- show which line your cursor is on
vim.opt.scrolloff = 3 -- minimal number of screen lines to keep above and below the cursor
vim.opt.sidescrolloff = 3 -- number of columns to keep when scrolling
vim.opt.confirm = true -- ask to save if unsaved while quitting
vim.opt.hidden = true -- don't write empty unsaved files
vim.opt.incsearch = true -- move on search
vim.opt.laststatus = 2 -- always show status bar
vim.opt.pumheight = 10 -- maximum number of items to show in the popup menu
vim.opt.shiftwidth = 2 -- tab shiftwidth
vim.opt.swapfile = false -- don't create useless files
vim.opt.tabstop = 2 -- tab tabstop
vim.opt.wb = false -- don't create useless files
vim.opt.wildmenu = true -- enable wild menu
vim.opt.wildmode = 'longest,full' -- wild menu completion
vim.opt.writebackup = false -- don't create useless files
