#!/bin/bash

# Adapted from code found at https://gist.github.com/1712320

setopt prompt_subst
autoload -U colors && colors

GIT_PROMPT_SYMBOL="%{$fg[blue]%}"
GIT_PROMPT_PREFIX="%{$fg[green]%} %{$reset_color%}"
GIT_PROMPT_SUFFIX="%{$fg[green]%}%{$reset_color%}"
GIT_PROMPT_AHEAD="%{$fg[red]%} ANUM%{$reset_color%}"
GIT_PROMPT_BEHIND="%{$fg[cyan]%} BNUM%{$reset_color%}"
GIT_PROMPT_MERGING="%{$fg_bold[red]%} !%{$reset_color%}"
GIT_PROMPT_UNTRACKED="%{$fg_bold[red]%} .%{$reset_color%}"
GIT_PROMPT_MODIFIED="%{$fg_bold[yellow]%} .%{$reset_color%}"
GIT_PROMPT_STAGED="%{$fg_bold[green]%} .%{$reset_color%}"

parse_git_branch() {
  (git symbolic-ref -q HEAD || git name-rev --name-only --no-undefined --always HEAD) 2> /dev/null
}

parse_git_state() {

  local GIT_STATE=""

  # A single `git status --porcelain=v2 --branch` call replaces the previous
  # 6-7 git subprocesses (log x2, rev-parse, ls-files, diff x2). We parse its
  # output in-shell to derive ahead/behind, unmerged, untracked, modified and
  # staged state.
  local git_status
  git_status="$(git status --porcelain=v2 --branch --untracked-files=normal 2> /dev/null)" || return

  local ahead=0 behind=0 unmerged=0 untracked=0 modified=0 staged=0
  local line ab xy
  while IFS= read -r line; do
    case "$line" in
      '# branch.ab '*)
        ab="${line#\# branch.ab }"      # e.g. "+2 -3"
        ahead="${ab%% *}"; ahead="${ahead#+}"
        behind="${ab##* }"; behind="${behind#-}"
        ;;
      '1 '*|'2 '*)
        xy="${line#? }"; xy="${xy%% *}"   # 2-char <XY> field
        [[ "${xy[1]}" != '.' ]] && staged=1
        [[ "${xy[2]}" != '.' ]] && modified=1
        ;;
      'u '*) unmerged=1 ;;
      '?'*)  untracked=1 ;;
    esac
  done <<< "$git_status"

  if [ "$ahead" -gt 0 ]; then
    GIT_STATE=$GIT_STATE${GIT_PROMPT_AHEAD//NUM/$ahead}
  fi

  if [ "$behind" -gt 0 ]; then
    GIT_STATE=$GIT_STATE${GIT_PROMPT_BEHIND//NUM/$behind}
  fi

  if [ "$unmerged" -eq 1 ]; then
    GIT_STATE=$GIT_STATE$GIT_PROMPT_MERGING
  fi

  if [ "$untracked" -eq 1 ]; then
    GIT_STATE=$GIT_STATE$GIT_PROMPT_UNTRACKED
  fi

  if [ "$modified" -eq 1 ]; then
    GIT_STATE=$GIT_STATE$GIT_PROMPT_MODIFIED
  fi

  if [ "$staged" -eq 1 ]; then
    GIT_STATE=$GIT_STATE$GIT_PROMPT_STAGED
  fi

  if [[ -n $GIT_STATE ]]; then
    echo "$GIT_PROMPT_PREFIX$GIT_STATE$GIT_PROMPT_SUFFIX"
  fi

}

git_prompt_string() {
  local git_where="$(parse_git_branch)"
  [ -n "$git_where" ] && echo "$GIT_PROMPT_SYMBOL$(parse_git_state)$GIT_PROMPT_PREFIX%{$fg[yellow]%}${git_where#(refs/heads/|tags/)}"
}

RPS1='$(git_prompt_string)'
