#!/bin/bash

# shellcheck disable=SC2123
PATH=''

# Android dev
# PATH=$PATH:$ANDROID_HOME/emulator
# PATH=$PATH:$ANDROID_HOME/tools
# PATH=$PATH:$ANDROID_HOME/tools/bin
# PATH=$PATH:$ANDROID_HOME/platform-tools

# Shitty Python thing
PATH=$PATH:$HOME/.pyenv/shims

# gif generation
PATH=$PATH:$HOME/git/gifgen

# Shitty ruby env
PATH=$PATH:$GEM_HOME/bin

# Go dev
PATH=$PATH:$GOPATH/bin

# bun
PATH=$PATH:$HOME/.bun/bin

# proto
PATH=$PATH:$HOME/.proto/bin

# ...
PATH=$PATH:./node_modules/.bin
PATH=$PATH:../../node_modules/.bin

# pnpm
PATH=$PATH:$PNPM_HOME

# lol..
PATH=$PATH:$HOME/endorsement/bin

PATH=$PATH:$HOME/bin
PATH=$PATH:$HOME/.local/bin
PATH=$PATH:$HOME/.yarn/bin
PATH=$PATH:$HOME/.cargo/bin

PATH=$PATH:/usr/local/bin
PATH=$PATH:/usr/bin
PATH=$PATH:/bin

PATH=$PATH:$ANDROID_HOME/emulator
PATH=$PATH:$ANDROID_HOME/platform-tools

export PATH
