#!/bin/bash

export ZAVATTA='192.99.2.67'

# let .profile manage .profile
alias prof='vim ~/.profile && sprof'
alias sprof='source ~/.profile'

# hehe
alias vim=nvim

# `ls` thoughts
alias lt='ls -lt'

# folders
alias gg='cd ~/git'
alias dl='cd ~/downloads'
alias dot='cd ~/dotfiles'
alias gogo="cd $GOPATH/src"
alias pp="cd ~/git/passport"
alias ac="cd ~/git/app-components"
alias rc="cd ~/git/react-components"
alias ma="cd ~/git/mjml-app"

# git
alias gd='git diff'
alias gits='git status'
alias gitp='git push'
alias gitc='git commit'
alias scaffold='git config --local user.name TheScaffolder && git config --local user.email spam@forpurpose.io && git commit --amend --author "TheScaffolder <spam@forpurpose.io>" && git config --local --unset user.email && git config --local --unset user.name'
alias unscaffold='git config --local user.name meriadec && git config --local user.email meriadec.pillet@gmail.com && git commit --amend --author "meriadec <meriadec.pillet@gmail.com>" && git config --local --unset user.email && git config --local --unset user.name'

# dev
vgrep () {
  vim $(grep -rn $1 src | cut -d : -f 1 | sort | uniq)
}

# wine

alias win-steam='wine ~/.wine/drive_c/Program\ Files\ \(x86\)/Steam/Steam.exe'
alias win-fl-studio='wine ~/.wine/drive_c/Program\ Files\ \(x86\)/Image-Line/FL\ Studio\ 12/FL.exe'

# random
alias sushi='$BROWSER https://www.planetsushi.fr/'
alias public-ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias ag='ag --color-path "1;34"'
alias dump='xsel -o | less'
alias g=$BROWSER
alias hdcast='ffcast -s ffmpeg -f x11grab -framerate 60 -show_region 1 -s %s -i %D+%c -c:v libx264rgb -crf 0 -preset ultrafast'
alias bye='shutdown now'

# Linux specifics
if [[ `uname` == 'Linux' ]]; then

  # clipboard copy
  alias pbcopy='xsel --clipboard --input'

  # purge memory
  alias purge='sync; echo 3 | sudo tee /proc/sys/vm/drop_caches'

  # open
  alias open=xdg-open

  say () {
     espeak -a 200 $1 2>/dev/null
  }

  download () {
    transmission-remote-cli -c $ZAVATTA $1
  }

fi

# OSX specifics
if [[ `uname` == 'Darwin' ]]; then

  # use retarded folder case
  alias dl='cd ~/Downloads'

fi
