#!/bin/bash

export ZAVATTA='192.99.2.67'

alias vim=nvim

# let .profile manage .profile
alias prof='vim ~/.profile && sprof'
alias sprof='source ~/.profile'

# hehe
alias vmi=vim
alias ivm=vim
alias pd=pwd
alias tgi=tig

# `ls` thoughts
alias lt='ls -lt'

# folders
alias gg='cd ~/git'
alias dl='cd ~/Downloads'
alias dot='cd ~/dotfiles'
alias ma="cd ~/git/mjml-app"
alias min="cd ~/git/minus"

alias api="cd ~/git/ledger-node-js-api"
alias hid="cd ~/git/ledger-node-js-hid"
alias app="cd ~/git/ledger-wallet-desktop"

# git
alias gd='git diff'
alias gb='git branch -vv'
alias gits='git status'
alias gtis='gits'
alias igts='gits'
alias gitp='git push'
alias gitc='git commit'
alias gfop='git fetch origin --prune'
alias gc='git checkout'
alias scaffold='git config --local user.name TheScaffolder && git config --local user.email spam@forpurpose.io && git commit --amend --author "TheScaffolder <spam@forpurpose.io>" && git config --local --unset user.email && git config --local --unset user.name'
alias unscaffold='git config --local user.name meriadec && git config --local user.email meriadec.pillet@gmail.com && git commit --amend --author "meriadec <meriadec.pillet@gmail.com>" && git config --local --unset user.email && git config --local --unset user.name'

# misc
alias vimup="vim +'PlugUpgrade|PlugInstall|PlugUpdate|qa!'"

# dev
vgrep () {
  vim $(grep -rn $1 src | cut -d : -f 1 | sort | uniq)
}

alias v='toOpen=$(fzf) && [ "$toOpen" != "" ] && vim $toOpen'

# random
alias sushi='$BROWSER https://www.planetsushi.fr/'
alias public-ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias ag='ag --color-path "1;34"'
alias dump='xsel -o | less'
alias g=$BROWSER
alias hdcast='ffcast -s ffmpeg -f x11grab -framerate 60 -show_region 1 -s %s -i %D+%c -c:v libx264rgb -crf 0 -preset ultrafast'
alias bye='shutdown now'
alias showfiles='cut -d : -f 1 | sort | uniq'
alias upd='pacaur -Syu --noconfirm'

# Linux specifics
if [[ `uname` == 'Linux' ]]; then

  # clipboard copy
  alias pbcopy='xsel --clipboard --input'

  # purge memory
  alias purge='sync; echo 3 | sudo tee /proc/sys/vm/drop_caches'

  # open
  alias open=xdg-open

  say () {
     espeak -a 200 $1 2>/dev/null
  }

fi
