#!/bin/zsh

export ZAVATTA='192.99.2.67'
export CAVERN='91.121.143.211'
export JOBS=max

# node-gyp build using all cores
export JOBS=max

# let .profile manage .profile
alias prof='vim ~/.profile && sprof'
alias sprof='source ~/.profile'

# hehe
alias vim=nvim
alias vmi=vim
alias ivm=vim
alias vi=vim
alias pd=pwd
alias tgi=tig
alias gti=git

# `ls` thoughts
function lh () {
  ls -1th --color=always | head -n ${1-1}
}

# folders
alias gg='cd ~/git'
alias le='cd ~/ledger'
alias dot='cd ~/dotfiles'
alias ma="cd ~/git/mjml-app"
alias min="cd ~/git/minus"
alias dl='cd ~/Downloads'

# ledger env
alias api="cd ~/ledger/ledger-node-js-api"
alias hid="cd ~/ledger/ledger-node-js-hid"
alias app="cd ~/ledger/ledger-live-desktop"
alias mob="cd ~/ledger/ledger-live-mobile"
alias com="cd ~/ledger/ledger-live-common"
alias bind="cd ~/ledger/lib-ledger-core-node-bindings"
alias js="cd ~/ledger/ledgerjs"
alias lib="cd ~/ledger/lib-ledger-core"
alias build="cd ~/ledger/lib-ledger-core-build"

# git
alias gd='git diff'
alias gb='git branch -vv'
alias gr='git remote -v'
alias gits='git status'
alias gtis='gits'
alias igts='gits'
alias gitp='git push'
alias gitc='git commit'
alias gfop='git fetch origin --prune'

alias scaffold='git config --local user.name TheScaffolder && git config --local user.email spam@forpurpose.io && git commit --amend --author "TheScaffolder <spam@forpurpose.io>" && git config --local --unset user.email && git config --local --unset user.name'
alias unscaffold='git config --local user.name meriadec && git config --local user.email meriadec.pillet@gmail.com && git commit --amend --author "meriadec <meriadec.pillet@gmail.com>" && git config --local --unset user.email && git config --local --unset user.name'

# misc
alias vimup="vim +'PlugUpgrade|PlugInstall|PlugUpdate|qa!'"
alias plop="notify-send -u critical -i ~/dotfiles/assets/rick.png Hey\!"
alias sss="killall slack ; (slack >/dev/null 2>/dev/null &)"

# random
alias public-ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias dump='xsel -o | less'
alias g=$BROWSER
alias hdcast='ffcast -s ffmpeg -f x11grab -framerate 60 -show_region 1 -s %s -i %D+%c -c:v libx264rgb -crf 0 -preset ultrafast'
alias bye='shutdown now'
alias upd='trizen -Syu'
alias ledger-live='ledger-live-desktop'

function snth () {
  ls -1t ~/Downloads \
    | fzf --height 10 \
    | sed "s/^/$(echo $HOME | sed 's/\//\\\//g')\/Downloads\//g"
}

# dev
vgrep () {
  vim $(grep -rn $1 src | cut -d : -f 1 | sort | uniq)
}

# Linux specifics
if [[ `uname` == 'Linux' ]]; then

  # clipboard copy
  alias pbcopy='xsel --clipboard --input'

  # purge memory
  alias purge='sync; echo 3 | sudo tee /proc/sys/vm/drop_caches'

  # open
  alias open=xdg-open

  say () {
     espeak -a 200 $1 2>/dev/null
  }

fi
