#!/bin/bash
# shellcheck disable=SC2155

cRed=$'%{\e[0;31m%}'
cYellow=$'%{\e[0;33m%}'
cBlue=$'%{\e[1;34m%}'
cNice=$'%{\e[0;36m%}'
cNop=$'%{\e[0;0m%}'

function lastExitCode() {
  local LAST_EXIT_CODE=$?
  if [[ $LAST_EXIT_CODE -ne 0 ]]; then
    echo "$cRed$LAST_EXIT_CODE$cNop"
  else
    echo $LAST_EXIT_CODE
  fi
}

if [[ $SSH_CLIENT != "" ]]; then
  export PS1='${cRed}%n${cNop} ${cNice}%m${cNop} $(lastExitCode) ${cYellow}%1~${cNop} ${cBlue}\$${cNop} '
else
  export PS1='$(lastExitCode) ${cYellow}%1~${cNop} ${cBlue}\$${cNop} '
fi
# export PS1="${hostName}$(lastExitCode) ${cYellow}%1~${cNop} ${cBlue}\$${cNop} "
