systemctl --user import-environment DISPLAY

setxkbmap dvp
setxkbmap -option compose:ralt

xset r rate 150 200
xset -b
xbindkeys

xrdb merge ~/.Xresources
eval "$(ssh-agent)"

exec picom &

feh --bg-scale ~/dotfiles/assets/images/bg.png

#base16-pick material

exec i3
