systemctl --user import-environment DISPLAY

setxkbmap dvp
setxkbmap -option compose:ralt

xset r rate 150 200
xset -b
xbindkeys

xrdb merge ~/.Xresources
eval "$(ssh-agent)"

exec compton &

cat \
  $HOME/.config/i3/base \
  $HOME/.config/i3/colors \
  > $HOME/.config/i3/config

exec i3
