#!/bin/bash
# shellcheck disable=SC2155,SC1126,SC1090

# ============================================================================ #
#                                                                              #
#                                    .zshrc                                    #
#                                                                              #
# ============================================================================ #

#    --------------------------------------------------------------------------#
# => globals                                                                   #
#    --------------------------------------------------------------------------#

# common

export TERMINAL=$TERM
export LANG=en_US.UTF-8

export EDITOR=nvim
export BROWSER=/usr/bin/google-chrome-stable

export LS_COLORS="ln=32:di=35;35:ex=40;31;01"
export GPG_TTY=$(tty)

# dev

export GOPATH=$HOME/dev/go
export BOLOS_ENV=$HOME/bolos
export BOLOS_SDK=$HOME/git/nanos-secure-sdk
export GEM_HOME=$HOME/.gem/ruby/2.6.0
# export NODE_OPTIONS="--max-old-space-size=8192"
# export ANDROID_HOME=/opt/android-sdk

#    --------------------------------------------------------------------------#
# => oh-my-zsh                                                                 #
#    --------------------------------------------------------------------------#

export ZSH=$HOME/.oh-my-zsh
# shellcheck disable=SC2034
CASE_SENSITIVE="true"
# shellcheck disable=SC2034
plugins=()
source "$ZSH/oh-my-zsh.sh"

#    --------------------------------------------------------------------------#
# => zsh-syntax-highlighting                                                   #
#    --------------------------------------------------------------------------#

source "$HOME/git/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

#    --------------------------------------------------------------------------#
# => fzf                                                                       #
#    --------------------------------------------------------------------------#

FZF_HOME=/usr/share/fzf

source "$FZF_HOME/completion.zsh"
source "$FZF_HOME/key-bindings.zsh"

export FZF_DEFAULT_COMMAND='rg -g !.git/ --hidden --files --follow'
export FZF_CTRL_T_COMMAND='rg --files --follow 2>/dev/null'

# nord theme
export FZF_DEFAULT_OPTS='
  --color=dark
  --color fg:#D8DEE9,bg:#2E3440,hl:#A3BE8C,fg+:#D8DEE9,bg+:#434C5E,hl+:#A3BE8C
  --color pointer:#BF616A,info:#4C566A,spinner:#4C566A,header:#4C566A,prompt:#81A1C1,marker:#EBCB8B
'

#    --------------------------------------------------------------------------#
# => ssh                                                                       #
#    --------------------------------------------------------------------------#

if [ -z "$SSH_AUTH_SOCK" ] ; then
  echo "> Starting ssh-agent"
  eval "$(ssh-agent -s)"
fi

if [ -n "$DISPLAY" ] && ! ssh-add -l >/dev/null; then
  ssh-add
fi

#    --------------------------------------------------------------------------#
# => modules                                                                   #
#    --------------------------------------------------------------------------#

export COMPOSE_FILE=/home/meri/ledger/vault-integration/docker-compose.yml

source "$HOME/.profile"
source "$HOME/.path"
source "$HOME/.gitprompt"
source "$HOME/.prompt"
source "$HOME/.private"

# eval "$(starship init zsh)"
