#!/bin/bash
# shellcheck disable=SC2155,SC1126,SC1090

# ============================================================================ #
#                                                                              #
#                                    .zshrc                                    #
#                                                                              #
# ============================================================================ #

#    --------------------------------------------------------------------------#
# => globals                                                                   #
#    --------------------------------------------------------------------------#

# common

export LANG=en_US.UTF-8
export EDITOR="$(command -v nvim)"
export LS_COLORS="ln=32:di=35;35:ex=40;31;01"
export GPG_TTY=$(tty)

# dev

export GOPATH=$HOME/dev/go
export BOLOS_ENV=$HOME/bolos
export BOLOS_SDK=$HOME/git/nanos-secure-sdk

if [[ $(uname) == 'Linux' ]]; then
  export ANDROID_HOME=/opt/android-sdk
  export BROWSER=/usr/sbin/google-chrome-unstable
  export TERMINAL=$TERM
fi

#    --------------------------------------------------------------------------#
# => oh-my-zsh                                                                 #
#    --------------------------------------------------------------------------#

export ZSH=$HOME/.oh-my-zsh
# shellcheck disable=SC2034
CASE_SENSITIVE="true"
# shellcheck disable=SC2034
plugins=()
source "$ZSH/oh-my-zsh.sh"

#    --------------------------------------------------------------------------#
# => zsh-syntax-highlighting                                                   #
#    --------------------------------------------------------------------------#

source "$HOME/git/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

#    --------------------------------------------------------------------------#
# => fzf                                                                       #
#    --------------------------------------------------------------------------#

export FZF_DEFAULT_COMMAND='rg --files --follow'
export FZF_CTRL_T_COMMAND='rg --files --follow 2>/dev/null'

fzfKeyBindings=/etc/profile.d/fzf.zsh
if [ -f $fzfKeyBindings ]; then
  source $fzfKeyBindings
fi

#    --------------------------------------------------------------------------#
# => base16                                                                    #
#    --------------------------------------------------------------------------#

BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
  [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
  eval "$("$BASE16_SHELL/profile_helper.sh")"

#    --------------------------------------------------------------------------#
# => ssh                                                                       #
#    --------------------------------------------------------------------------#

if [ -z "$SSH_AUTH_SOCK" ] ; then
  echo "> Starting ssh-agent"
  eval "ssh-agent -s"
fi

if [ -n "$DISPLAY" ] && ! ssh-add -l >/dev/null; then
  ssh-add
fi

#    --------------------------------------------------------------------------#
# => modules                                                                   #
#    --------------------------------------------------------------------------#

source "$HOME/.private"
source "$HOME/.profile"
source "$HOME/.gitprompt"
source "$HOME/.prompt"
source "$HOME/.path"
