#!/bin/bash

source scripts/utils.sh
source theme.sh

TEMPLATE_FILES=$(find dot config -name '*.template')
TEMPLATE_FILES_NB=$(echo $TEMPLATE_FILES | wc -l)

TMP_FILE=$(mktemp)

function REPLACE {
  IN=$1
  OUT=$2
  if [[ `uname` == 'Darwin' ]]; then
    sed -i ".bak" "s/$\[$IN\]/$OUT/g" $TMP_FILE
  else
    sed --in-place "s/$\[$IN\]/$OUT/g" $TMP_FILE
  fi
}

for TEMPLATE_FILE in $TEMPLATE_FILES; do
  DIRNAME=$(dirname -- "$TEMPLATE_FILE")
  FILENAME=$(basename -- "$TEMPLATE_FILE")
  TRIMMED="${FILENAME%.*}"
  TARGET="$DIRNAME/$TRIMMED"

  cp $TEMPLATE_FILE $TMP_FILE
  REPLACE "DPI" $DPI
  REPLACE "COLOR_FOREGROUND" $COLOR_FOREGROUND
  REPLACE "COLOR_BACKGROUND" $COLOR_BACKGROUND
  REPLACE "COLOR_CURSOR" $COLOR_CURSOR
  REPLACE "COLOR_COLOR0" $COLOR_COLOR0
  REPLACE "COLOR_COLOR1" $COLOR_COLOR1
  REPLACE "COLOR_COLOR2" $COLOR_COLOR2
  REPLACE "COLOR_COLOR3" $COLOR_COLOR3
  REPLACE "COLOR_COLOR4" $COLOR_COLOR4
  REPLACE "COLOR_COLOR5" $COLOR_COLOR5
  REPLACE "COLOR_COLOR6" $COLOR_COLOR6
  REPLACE "COLOR_COLOR7" $COLOR_COLOR7
  REPLACE "COLOR_COLOR8" $COLOR_COLOR8
  REPLACE "COLOR_COLOR9" $COLOR_COLOR9
  REPLACE "COLOR_COLOR10" $COLOR_COLOR10
  REPLACE "COLOR_COLOR11" $COLOR_COLOR11
  REPLACE "COLOR_COLOR12" $COLOR_COLOR12
  REPLACE "COLOR_COLOR13" $COLOR_COLOR13
  REPLACE "COLOR_COLOR14" $COLOR_COLOR14
  REPLACE "COLOR_COLOR15" $COLOR_COLOR15
  REPLACE "AWESOME_SCREEN_PADDING" $AWESOME_SCREEN_PADDING
  cp $TMP_FILE $TARGET

  LOG "compiled $TARGET"
done

rm $TMP_FILE
LOG "compile success"
