#!/bin/bash

OUTPUT=$(curl -s -X GET "https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=eur" -H "accept: application/json" --fail)
if [[ "$OUTPUT" != "" ]]; then
  echo "$(
    echo "$OUTPUT" \
      | jq '.ethereum.eur' \
      | cut -d '.' -f 1 \
      | xargs printf "%'.f"
  ) EUR"
else
  echo "(rate limit)"
fi
